<h1>导入数据</h1>

In [1]:
import matplotlib.pyplot as plt
import tensorflow as tf
import pandas as pd
import time
import tensorflow.keras.backend as K
from datetime import datetime
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, f1_score
from sklearn.utils.class_weight import compute_class_weight
from tqdm import tqdm
from tensorflow.keras.layers import Input, Dense, LSTM, MaxPool1D, Dropout, concatenate, Flatten, Conv1D
from tensorflow.keras.callbacks import History, TensorBoard, EarlyStopping
from tensorflow.keras.backend import clear_session
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.models import Model
from time import strftime, localtime

<h1>数据处理</h1>

<h2>数据预处理</h2>

<h3>conf_info数据预处理</h3>

In [2]:
cons_info = pd.read_csv("../data/训练组_比特币挖矿_档案明细（20211220）.csv", index_col=0, quotechar='"', encoding="gbk")
cons_info

              ID ELEC_TYPE_NAME VOLT_NAME  ... TMP_NAME  TMP_DATE  IS_FLAG
                                           ...
1      329465205       乡村居民生活用电    交流220V  ...    非临时用电       NaN        0
2      329465245       乡村居民生活用电    交流220V  ...    非临时用电       NaN        0
3      329465357       乡村居民生活用电    交流220V  ...    非临时用电       NaN        0
4      329465360       乡村居民生活用电    交流220V  ...    非临时用电       NaN        0
5      329465439       乡村居民生活用电    交流220V  ...    非临时用电       NaN        0
...          ...            ...       ...  ...      ...       ...      ...
8836  2862711473       乡村居民生活用电    交流380V  ...    非临时用电       NaN        0
8837  2864274650       乡村居民生活用电    交流220V  ...    非临时用电       NaN        0
8838  2872313739       乡村居民生活用电    交流380V  ...    非临时用电       NaN        0
8839  2872314719       乡村居民生活用电    交流380V  ...    非临时用电       NaN        0
8840  2529558569       城镇居民生活用电    交流380V  ...    非临时用电       NaN        0

[8840 rows x 14 columns]

In [3]:
cons_info = cons_info.set_index("ID").drop(columns=["CANCEL_DATE", "TMP_DATE"])
cons_info

           ELEC_TYPE_NAME VOLT_NAME  ... TMP_NAME  IS_FLAG
ID                                   ...
329465205        乡村居民生活用电    交流220V  ...    非临时用电        0
329465245        乡村居民生活用电    交流220V  ...    非临时用电        0
329465357        乡村居民生活用电    交流220V  ...    非临时用电        0
329465360        乡村居民生活用电    交流220V  ...    非临时用电        0
329465439        乡村居民生活用电    交流220V  ...    非临时用电        0
...                   ...       ...  ...      ...      ...
2862711473       乡村居民生活用电    交流380V  ...    非临时用电        0
2864274650       乡村居民生活用电    交流220V  ...    非临时用电        0
2872313739       乡村居民生活用电    交流380V  ...    非临时用电        0
2872314719       乡村居民生活用电    交流380V  ...    非临时用电        0
2529558569       城镇居民生活用电    交流380V  ...    非临时用电        0

[8840 rows x 11 columns]

In [4]:
cons_info["BUILD_DATE"] = pd.to_datetime(cons_info["BUILD_DATE"])
cons_info["LAST_CHK_DATE"] = pd.to_datetime(cons_info["LAST_CHK_DATE"])
cons_info

           ELEC_TYPE_NAME VOLT_NAME  ... TMP_NAME  IS_FLAG
ID                                   ...
329465205        乡村居民生活用电    交流220V  ...    非临时用电        0
329465245        乡村居民生活用电    交流220V  ...    非临时用电        0
329465357        乡村居民生活用电    交流220V  ...    非临时用电        0
329465360        乡村居民生活用电    交流220V  ...    非临时用电        0
329465439        乡村居民生活用电    交流220V  ...    非临时用电        0
...                   ...       ...  ...      ...      ...
2862711473       乡村居民生活用电    交流380V  ...    非临时用电        0
2864274650       乡村居民生活用电    交流220V  ...    非临时用电        0
2872313739       乡村居民生活用电    交流380V  ...    非临时用电        0
2872314719       乡村居民生活用电    交流380V  ...    非临时用电        0
2529558569       城镇居民生活用电    交流380V  ...    非临时用电        0

[8840 rows x 11 columns]

In [5]:
cons_info["SHIFT_NO"] = cons_info["SHIFT_NO"].fillna(0)
cons_info

           ELEC_TYPE_NAME VOLT_NAME  ... TMP_NAME  IS_FLAG
ID                                   ...
329465205        乡村居民生活用电    交流220V  ...    非临时用电        0
329465245        乡村居民生活用电    交流220V  ...    非临时用电        0
329465357        乡村居民生活用电    交流220V  ...    非临时用电        0
329465360        乡村居民生活用电    交流220V  ...    非临时用电        0
329465439        乡村居民生活用电    交流220V  ...    非临时用电        0
...                   ...       ...  ...      ...      ...
2862711473       乡村居民生活用电    交流380V  ...    非临时用电        0
2864274650       乡村居民生活用电    交流220V  ...    非临时用电        0
2872313739       乡村居民生活用电    交流380V  ...    非临时用电        0
2872314719       乡村居民生活用电    交流380V  ...    非临时用电        0
2529558569       城镇居民生活用电    交流380V  ...    非临时用电        0

[8840 rows x 11 columns]

In [6]:
cons_info["now"] = "2021-12-31"
cons_info["now"] = pd.to_datetime(cons_info["now"])
cons_info

           ELEC_TYPE_NAME VOLT_NAME  ... IS_FLAG        now
ID                                   ...
329465205        乡村居民生活用电    交流220V  ...       0 2021-12-31
329465245        乡村居民生活用电    交流220V  ...       0 2021-12-31
329465357        乡村居民生活用电    交流220V  ...       0 2021-12-31
329465360        乡村居民生活用电    交流220V  ...       0 2021-12-31
329465439        乡村居民生活用电    交流220V  ...       0 2021-12-31
...                   ...       ...  ...     ...        ...
2862711473       乡村居民生活用电    交流380V  ...       0 2021-12-31
2864274650       乡村居民生活用电    交流220V  ...       0 2021-12-31
2872313739       乡村居民生活用电    交流380V  ...       0 2021-12-31
2872314719       乡村居民生活用电    交流380V  ...       0 2021-12-31
2529558569       城镇居民生活用电    交流380V  ...       0 2021-12-31

[8840 rows x 12 columns]

In [7]:
cons_info["live_days"] = (cons_info["now"] - cons_info["BUILD_DATE"]).map(lambda x: x.days)
cons_info["check_days"] = (cons_info["now"] - cons_info["LAST_CHK_DATE"]).map(lambda x: x.days)
cons_info

           ELEC_TYPE_NAME VOLT_NAME  ... live_days  check_days
ID                                   ...
329465205        乡村居民生活用电    交流220V  ...      6040        6040
329465245        乡村居民生活用电    交流220V  ...      6040        6040
329465357        乡村居民生活用电    交流220V  ...      6040        6040
329465360        乡村居民生活用电    交流220V  ...      6040        6040
329465439        乡村居民生活用电    交流220V  ...      6040        6040
...                   ...       ...  ...       ...         ...
2862711473       乡村居民生活用电    交流380V  ...       759         759
2864274650       乡村居民生活用电    交流220V  ...       758         758
2872313739       乡村居民生活用电    交流380V  ...       743         743
2872314719       乡村居民生活用电    交流380V  ...       741         741
2529558569       城镇居民生活用电    交流380V  ...      1430        1430

[8840 rows x 14 columns]

In [8]:
cons_info = cons_info.drop(columns=["BUILD_DATE", "LAST_CHK_DATE", "now"])
cons_info

           ELEC_TYPE_NAME VOLT_NAME  ... live_days  check_days
ID                                   ...
329465205        乡村居民生活用电    交流220V  ...      6040        6040
329465245        乡村居民生活用电    交流220V  ...      6040        6040
329465357        乡村居民生活用电    交流220V  ...      6040        6040
329465360        乡村居民生活用电    交流220V  ...      6040        6040
329465439        乡村居民生活用电    交流220V  ...      6040        6040
...                   ...       ...  ...       ...         ...
2862711473       乡村居民生活用电    交流380V  ...       759         759
2864274650       乡村居民生活用电    交流220V  ...       758         758
2872313739       乡村居民生活用电    交流380V  ...       743         743
2872314719       乡村居民生活用电    交流380V  ...       741         741
2529558569       城镇居民生活用电    交流380V  ...      1430        1430

[8840 rows x 11 columns]

In [9]:
cons_info.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8840 entries, 329465205 to 2529558569
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ELEC_TYPE_NAME  8840 non-null   object
 1   VOLT_NAME       8840 non-null   object
 2   PRC_NAME        8840 non-null   object
 3   CONTRACT_CAP    8840 non-null   float64
 4   RUN_CAP         8840 non-null   float64
 5   SHIFT_NO        8840 non-null   float64
 6   CHK_CYCLE       8838 non-null   float64
 7   TMP_NAME        8840 non-null   object
 8   IS_FLAG         8840 non-null   int64
 9   live_days       8840 non-null   int64
 10  check_days      8840 non-null   int64
dtypes: float64(4), int64(3), object(4)
memory usage: 828.8+ KB

In [10]:
cons_info = pd.get_dummies(cons_info)
cons_info

            CONTRACT_CAP  RUN_CAP  ...  PRC_NAME_居民合表电价(不满1千伏）  TMP_NAME_非临时用电
ID                                 ...
329465205            4.0      4.0  ...                       1               1
329465245            4.0      4.0  ...                       1               1
329465357            8.0      8.0  ...                       1               1
329465360            2.0      2.0  ...                       1               1
329465439            8.0      8.0  ...                       1               1
...                  ...      ...  ...                     ...             ...
2862711473          39.0     39.0  ...                       1               1
2864274650          13.0     13.0  ...                       1               1
2872313739          39.0     39.0  ...                       1               1
2872314719          39.0     39.0  ...                       1               1
2529558569          30.0     30.0  ...                       1               1

[8840 rows x 21 columns]

<h3>elec_month数据预处理</h3>

In [11]:
elec_month = pd.read_csv("../data/训练组_比特币挖矿_月用电明细（20211217）.csv")
elec_month

                id      ym  pq_f  pq_g  pq_p  pq_z
0        329769614  202001   615   161     0   776
1        329769614  202002   492   154    -1   645
2        329769614  202003   457   114     1   572
3        329769614  202004   522   171     0   693
4        329769614  202005   519   181     0   700
...            ...     ...   ...   ...   ...   ...
194475  2878334859  202106   107    67    -1   173
194476  2878334859  202107   170   112     1   283
194477  2878334859  202108   102    67     0   169
194478  2878334859  202109   112    65    -1   176
194479  2878334859  202110   144    84     1   229

[194480 rows x 6 columns]

In [12]:
elec_month["ym"] = elec_month["ym"].astype(str)
elec_month

                id      ym  pq_f  pq_g  pq_p  pq_z
0        329769614  202001   615   161     0   776
1        329769614  202002   492   154    -1   645
2        329769614  202003   457   114     1   572
3        329769614  202004   522   171     0   693
4        329769614  202005   519   181     0   700
...            ...     ...   ...   ...   ...   ...
194475  2878334859  202106   107    67    -1   173
194476  2878334859  202107   170   112     1   283
194477  2878334859  202108   102    67     0   169
194478  2878334859  202109   112    65    -1   176
194479  2878334859  202110   144    84     1   229

[194480 rows x 6 columns]

In [13]:
elec_month[["pq_f", "pq_g", "pq_p", "pq_z"]] = elec_month[["pq_f", "pq_g", "pq_p", "pq_z"]] / elec_month[["pq_f", "pq_g", "pq_p", "pq_z"]].max(axis=0)
elec_month

                id      ym      pq_f      pq_g      pq_p      pq_z
0        329769614  202001  0.018825  0.009651  0.000000  0.010450
1        329769614  202002  0.015060  0.009232 -0.000036  0.008686
2        329769614  202003  0.013988  0.006834  0.000036  0.007703
3        329769614  202004  0.015978  0.010251  0.000000  0.009332
4        329769614  202005  0.015886  0.010850  0.000000  0.009426
...            ...     ...       ...       ...       ...       ...
194475  2878334859  202106  0.003275  0.004016 -0.000036  0.002330
194476  2878334859  202107  0.005204  0.006714  0.000036  0.003811
194477  2878334859  202108  0.003122  0.004016  0.000000  0.002276
194478  2878334859  202109  0.003428  0.003896 -0.000036  0.002370
194479  2878334859  202110  0.004408  0.005035  0.000036  0.003084

[194480 rows x 6 columns]

In [14]:
cons_month_result = []
for cons_id in tqdm(cons_info.index):
    df = elec_month[elec_month["id"] == cons_id]
    df1 = df.drop(columns=["id"]).sort_values("ym").drop(columns=["ym"])
    cons_month_result.append(df1.values)
cons_month = np.array(cons_month_result)
cons_month.shape

100%|█████████████████████████████████| 8840/8840 [00:13<00:00, 677.86it/s]

(8840, 22, 4)

<h3>elec_day数据预处理</h3>

In [15]:
elec_day = pd.read_csv("../data/训练组_比特币挖矿_日用电明细（20211217）.csv")
elec_day

                id                   rq  ...  kwh_pap_r3  kwh_pap_r4
0        329449398  2020-01-22 00:00:00  ...         0.0        4.36
1        329449398  2020-01-23 00:00:00  ...         0.0        7.86
2        329449398  2020-01-24 00:00:00  ...         0.0        5.36
3        329449398  2020-01-25 00:00:00  ...         0.0        4.43
4        329449398  2020-01-26 00:00:00  ...         0.0        4.52
...            ...                  ...  ...         ...         ...
954564  2878334859  2021-10-05 00:00:00  ...         0.0        2.73
954565  2878334859  2021-10-06 00:00:00  ...         0.0        2.74
954566  2878334859  2021-10-07 00:00:00  ...         0.0        2.73
954567  2878334859  2021-10-08 00:00:00  ...         0.0        2.73
954568  2878334859  2021-10-09 00:00:00  ...         0.0        2.73

[954569 rows x 8 columns]

In [16]:
elec_day[["kwh", "kwh_rap", "kwh_pap_r1", "kwh_pap_r2", "kwh_pap_r3", "kwh_pap_r4"]] = elec_day[["kwh", "kwh_rap", "kwh_pap_r1", "kwh_pap_r2", "kwh_pap_r3", "kwh_pap_r4"]] / elec_day[["kwh", "kwh_rap", "kwh_pap_r1", "kwh_pap_r2", "kwh_pap_r3", "kwh_pap_r4"]].max(axis=0)
elec_day

                id                   rq  ...  kwh_pap_r3  kwh_pap_r4
0        329449398  2020-01-22 00:00:00  ...         0.0    0.000450
1        329449398  2020-01-23 00:00:00  ...         0.0    0.000811
2        329449398  2020-01-24 00:00:00  ...         0.0    0.000553
3        329449398  2020-01-25 00:00:00  ...         0.0    0.000457
4        329449398  2020-01-26 00:00:00  ...         0.0    0.000466
...            ...                  ...  ...         ...         ...
954564  2878334859  2021-10-05 00:00:00  ...         0.0    0.000282
954565  2878334859  2021-10-06 00:00:00  ...         0.0    0.000283
954566  2878334859  2021-10-07 00:00:00  ...         0.0    0.000282
954567  2878334859  2021-10-08 00:00:00  ...         0.0    0.000282
954568  2878334859  2021-10-09 00:00:00  ...         0.0    0.000282

[954569 rows x 8 columns]

In [17]:
elec_day = elec_day.fillna(0)
elec_day

                id                   rq  ...  kwh_pap_r3  kwh_pap_r4
0        329449398  2020-01-22 00:00:00  ...         0.0    0.000450
1        329449398  2020-01-23 00:00:00  ...         0.0    0.000811
2        329449398  2020-01-24 00:00:00  ...         0.0    0.000553
3        329449398  2020-01-25 00:00:00  ...         0.0    0.000457
4        329449398  2020-01-26 00:00:00  ...         0.0    0.000466
...            ...                  ...  ...         ...         ...
954564  2878334859  2021-10-05 00:00:00  ...         0.0    0.000282
954565  2878334859  2021-10-06 00:00:00  ...         0.0    0.000283
954566  2878334859  2021-10-07 00:00:00  ...         0.0    0.000282
954567  2878334859  2021-10-08 00:00:00  ...         0.0    0.000282
954568  2878334859  2021-10-09 00:00:00  ...         0.0    0.000282

[954569 rows x 8 columns]

In [18]:
dates = pd.to_datetime(elec_day["rq"].unique()).sort_values()

In [19]:
cons_day_result = []
for cons_id in tqdm(cons_info.index):
    df = elec_day[elec_day["id"] == cons_id].drop(columns=["id"]).sort_values("rq")
    df["rq"] = pd.to_datetime(df["rq"])
    df = df.set_index("rq")
    df = df.reindex(dates).fillna(0)
    cons_day_result.append(df.values)
cons_day = np.array(cons_day_result)
cons_day.shape

100%|█████████████████████████████████| 8840/8840 [00:23<00:00, 369.95it/s]

(8840, 108, 6)

<h2>查看处理好的结果</h2>

<h3>标签</h3>

In [20]:
target = cons_info["IS_FLAG"].values.astype(np.float64)

<h3>统一视图</h3>

In [21]:
cons_info = cons_info.drop(columns=["IS_FLAG"]).values
cons_info.shape

(8840, 20)

<h3>月均电量</h3>

In [22]:
cons_month.shape

(8840, 22, 4)

<h3>日电量</h3>

In [23]:
cons_day.shape

(8840, 108, 6)

<h2>对正样本重复</h2>

In [24]:
cons_info_pos = cons_info[target == 1].repeat(800, axis=0)
cons_info_pos.shape

(8000, 20)

In [25]:
cons_month_pos = cons_month[target == 1].repeat(800, axis=0)
cons_month_pos.shape

(8000, 22, 4)

In [26]:
cons_day_pos = cons_day[target == 1].repeat(800, axis=0)
cons_day_pos.shape

(8000, 108, 6)

<h2>提取负样本</h2>

In [27]:
cons_info_neg = cons_info[target == 0]
cons_month_neg = cons_month[target == 0]
cons_day_neg = cons_day[target == 0]
print(cons_info_neg.shape)
print(cons_month_neg.shape)
print(cons_day_neg.shape)

(8830, 20)
(8830, 22, 4)
(8830, 108, 6)

<h2>合并正负样本</h2>

In [28]:
cons_info = np.concatenate([cons_info_pos, cons_info_neg], axis=0)
cons_month = np.concatenate([cons_month_pos, cons_month_neg], axis=0)
cons_day = np.concatenate([cons_day_pos, cons_day_neg], axis=0)
print(cons_info.shape)
print(cons_month.shape)
print(cons_day.shape)

(16830, 20)
(16830, 22, 4)
(16830, 108, 6)

<h2>重复标签</h2>

In [29]:
target_pos = target[target == 1]
target_neg = target[target == 0]
target_pos = target_pos.repeat(800, axis=0)
target = np.concatenate([target_pos, target_neg], axis=0)
print(target.shape)

(16830,)

<h1>构建模型</h1>

<h2>初始化tensorflow</h2>

In [30]:
clear_session()
tf.compat.v1.reset_default_graph()
for gpu in tf.config.list_physical_devices("GPU"):
    tf.config.experimental.set_memory_growth(gpu, True)

<h2>构建模型</h2>

In [31]:
def build_model(cons_info_shape, cons_month_shape, cons_day_shape) -> Model:
    input_cons_info = Input(shape=cons_info_shape, name="input_cons_info")
    input_cons_month = Input(shape=cons_month_shape, name="input_cons_month")
    input_cons_day = Input(shape=cons_day_shape, name="input_cons_day")
    
    x1 = Dense(units=32, activation="relu", name="x1")(input_cons_info)
    x2 = Dense(units=64, activation="relu", name="x2")(x1)
    x3 = Dropout(0.2, name="x3")(x2)
    
    y11 = Conv1D(filters=16, kernel_size=5, strides=1, padding="causal", activation="relu", name="conv1d_y1")(input_cons_month)
    y12 = MaxPool1D(pool_size=5, strides=1, padding="valid", name="max_pool1d_y1")(y11)
    y13 = Conv1D(filters=32, kernel_size=3, strides=1, padding="causal", activation="relu", name="conv1d_y2")(y12)
    y14 = MaxPool1D(pool_size=3, strides=1, padding="valid", name="max_pool1d_y2")(y13)
    y1, y_hidden_state, y_cell_state = LSTM(units=16, return_sequences=True, return_state=True, name="y1")(y14)
    y_hidden_state_1 = Dense(units=64, name="y_hidden_state_1")(y_hidden_state)
    y_cell_state_1 = Dense(units=64, name="y_cell_state_1")(y_cell_state)
    y2 = LSTM(units=64, return_sequences=True, return_state=False, name="y2")(y1, [y_hidden_state_1, y_cell_state_1])
    
    z11 = Conv1D(filters=16, kernel_size=5, strides=1, padding="causal", activation="relu", name="conv1d_z1")(input_cons_day)
    z12 = MaxPool1D(pool_size=5, strides=1, padding="valid", name="max_pool1d_z1")(z11)
    z13 = Conv1D(filters=32, kernel_size=3, strides=1, padding="causal", activation="relu", name="conv1d_z2")(z12)
    z14 = MaxPool1D(pool_size=3, strides=1, padding="valid", name="max_pool1d_z2")(z13)
    z1, z_hidden_state, z_cell_state = LSTM(units=16, return_sequences=True, return_state=True, name="z1")(z14)
    z_hidden_state_1 = Dense(units=64, name="z_hidden_state_1")(z_hidden_state)
    z_cell_state_1 = Dense(units=64, name="z_cell_state_1")(z_cell_state)
    z2 = LSTM(units=64, return_sequences=True, return_state=False, name="z2")(z1, [z_hidden_state_1, z_cell_state_1])
    
    s1 = concatenate([y2, z2], axis=1, name="s1")
    s2 = LSTM(units=16, return_sequences=True, return_state=False, name="s2")(s1)
    s3 = LSTM(units=8, return_sequences=True, return_state=False, name="s3")(s2)
    s4 = Flatten(name="s4")(s3)
    s5 = Dropout(0.2, name="s5")(s4)
    
    o1 = concatenate([x3, s5], axis=-1, name="o1")
    o2 = Dense(units=64, name="o2")(o1)
    o3 = Dense(units=16, name="o3")(o2)
    o4 = Dropout(0.2, name="o4")(o3)
    o5 = Dense(units=1, name="o5")(o4)
    
    result = Model(inputs=[input_cons_info, input_cons_month, input_cons_day], outputs=[o4], name="mining-detector")
    result.summary()
    return result

In [32]:
def recall_m(y_true, y_pred):
    true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
    possible_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
    recall = true_positives / (possible_positives + K.epsilon())
    return recall

def precision_m(y_true, y_pred):
    true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
    predicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
    precision = true_positives / (predicted_positives + K.epsilon())
    return precision

def f1_m(y_true, y_pred):
    precision = precision_m(y_true, y_pred)
    recall = recall_m(y_true, y_pred)
    return 2*((precision*recall)/(precision+recall+K.epsilon()))

In [33]:
model = build_model(cons_info.shape[1:], cons_month.shape[1:], cons_day.shape[1:])
model.compile(
    optimizer='adam', 
    loss="binary_crossentropy", 
    metrics=["accuracy", recall_m, precision_m, f1_m]
)

Model: "mining-detector"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to
==================================================================================================
input_cons_month (InputLayer)   [(None, 22, 4)]      0
__________________________________________________________________________________________________
input_cons_day (InputLayer)     [(None, 108, 6)]     0
__________________________________________________________________________________________________
conv1d_y1 (Conv1D)              (None, 22, 16)       336         input_cons_month[0][0]
__________________________________________________________________________________________________
conv1d_z1 (Conv1D)              (None, 108, 16)      496         input_cons_day[0][0]
__________________________________________________________________________________________________
max_pool1d_y1 (MaxPooling1D)    (None, 18, 16)       0           conv1d_y1[0][0]
__________________________________________________________________________________________________
max_pool1d_z1 (MaxPooling1D)    (None, 104, 16)      0           conv1d_z1[0][0]
__________________________________________________________________________________________________
conv1d_y2 (Conv1D)              (None, 18, 32)       1568        max_pool1d_y1[0][0]
__________________________________________________________________________________________________
conv1d_z2 (Conv1D)              (None, 104, 32)      1568        max_pool1d_z1[0][0]
__________________________________________________________________________________________________
max_pool1d_y2 (MaxPooling1D)    (None, 16, 32)       0           conv1d_y2[0][0]
__________________________________________________________________________________________________
max_pool1d_z2 (MaxPooling1D)    (None, 102, 32)      0           conv1d_z2[0][0]
__________________________________________________________________________________________________
y1 (LSTM)                       [(None, 16, 16), (No 3136        max_pool1d_y2[0][0]
__________________________________________________________________________________________________
z1 (LSTM)                       [(None, 102, 16), (N 3136        max_pool1d_z2[0][0]
__________________________________________________________________________________________________
y_hidden_state_1 (Dense)        (None, 64)           1088        y1[0][1]
__________________________________________________________________________________________________
y_cell_state_1 (Dense)          (None, 64)           1088        y1[0][2]
__________________________________________________________________________________________________
z_hidden_state_1 (Dense)        (None, 64)           1088        z1[0][1]
__________________________________________________________________________________________________
z_cell_state_1 (Dense)          (None, 64)           1088        z1[0][2]
__________________________________________________________________________________________________
y2 (LSTM)                       (None, 16, 64)       20736       y1[0][0]
                                                                 y_hidden_state_1[0][0]
                                                                 y_cell_state_1[0][0]
__________________________________________________________________________________________________
z2 (LSTM)                       (None, 102, 64)      20736       z1[0][0]
                                                                 z_hidden_state_1[0][0]
                                                                 z_cell_state_1[0][0]
__________________________________________________________________________________________________
s1 (Concatenate)                (None, 118, 64)      0           y2[0][0]
                                                                 z2[0][0]
__________________________________________________________________________________________________
input_cons_info (InputLayer)    [(None, 20)]         0
__________________________________________________________________________________________________
s2 (LSTM)                       (None, 118, 16)      5184        s1[0][0]
__________________________________________________________________________________________________
x1 (Dense)                      (None, 32)           672         input_cons_info[0][0]
__________________________________________________________________________________________________
s3 (LSTM)                       (None, 118, 8)       800         s2[0][0]
__________________________________________________________________________________________________
x2 (Dense)                      (None, 64)           2112        x1[0][0]
__________________________________________________________________________________________________
s4 (Flatten)                    (None, 944)          0           s3[0][0]
__________________________________________________________________________________________________
x3 (Dropout)                    (None, 64)           0           x2[0][0]
__________________________________________________________________________________________________
s5 (Dropout)                    (None, 944)          0           s4[0][0]
__________________________________________________________________________________________________
o1 (Concatenate)                (None, 1008)         0           x3[0][0]
                                                                 s5[0][0]
__________________________________________________________________________________________________
o2 (Dense)                      (None, 64)           64576       o1[0][0]
__________________________________________________________________________________________________
o3 (Dense)                      (None, 16)           1040        o2[0][0]
__________________________________________________________________________________________________
o4 (Dropout)                    (None, 16)           0           o3[0][0]
==================================================================================================
Total params: 130,448
Trainable params: 130,448
Non-trainable params: 0
__________________________________________________________________________________________________

<h2>训练模型</h2>

<h3>设置class_weight和sample_weight</h3>

In [34]:
class_weight = compute_class_weight('balanced', np.unique(target) ,target)
class_weights = dict()
for class_name, weight in enumerate(class_weight):
    class_weights[class_name] = weight
    
sample_weights = np.ones(shape=(len(target),))
sample_weights[target == 1] = 800

c:\users\drzon\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\validation.py:70: FutureWarning: Pass classes=[0. 1.], y=[1. 1. 1. ... 0. 0. 0.] as keyword args. From version 0.25 passing these as positional arguments will result in an error
  FutureWarning)

<h3>开始训练</h3>

In [35]:
model.fit(
    [cons_info, cons_month, cons_day], 
    target, 
    validation_split=0.2,
    epochs=100, 
    batch_size=32, 
    use_multiprocessing=True, 
    workers=12,
    callbacks=[
        TensorBoard(log_dir="../logs/%s" % strftime("%Y%m%d_%H.%M.%S", localtime()), write_graph=True, write_images=True),
        EarlyStopping(monitor="val_loss", min_delta=1e-4, patience=10, restore_best_weights=True)
    ]
)

Epoch 1/100
  1/421 [..............................] - ETA: 0s - loss: 7.4433 - accuracy: 0.0000e+00 - recall_m: 5.6250 - precision_m: 0.5233 - f1_m: 0.9574WARNING:tensorflow:From c:\users\drzon\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\ops\summary_ops_v2.py:1277: stop (from tensorflow.python.eager.profiler) is deprecated and will be removed after 2020-07-01.
Instructions for updating:
use `tf.profiler.experimental.stop` instead.
  2/421 [..............................] - ETA: 1:05 - loss: 7.6731 - accuracy: 0.0000e+00 - recall_m: 5.6546 - precision_m: 0.5684 - f1_m: 1.0326WARNING:tensorflow:Callbacks method `on_train_batch_end` is slow compared to the batch time (batch time: 0.0360s vs `on_train_batch_end` time: 0.2587s). Check your callbacks.
421/421 [==============================] - 13s 31ms/step - loss: 7.5728 - accuracy: 0.0000e+00 - recall_m: 8.5569 - precision_m: 0.5941 - f1_m: 1.1094 - val_loss: 10.4838 - val_accuracy: 0.0000e+00 - val_recall_m: 0.0000e+00 - val_precision_m: 0.0000e+00 - val_f1_m: 0.0000e+00
Epoch 2/100
421/421 [==============================] - 11s 26ms/step - loss: 7.4368 - accuracy: 0.0000e+00 - recall_m: 9.2811 - precision_m: 0.5943 - f1_m: 1.1155 - val_loss: 11.4358 - val_accuracy: 0.0000e+00 - val_recall_m: 0.0000e+00 - val_precision_m: 0.0000e+00 - val_f1_m: 0.0000e+00
Epoch 3/100
421/421 [==============================] - 11s 27ms/step - loss: 7.3794 - accuracy: 0.0000e+00 - recall_m: 9.5958 - precision_m: 0.5941 - f1_m: 1.1174 - val_loss: 11.4358 - val_accuracy: 0.0000e+00 - val_recall_m: 0.0000e+00 - val_precision_m: 0.0000e+00 - val_f1_m: 0.0000e+00
Epoch 4/100
421/421 [==============================] - 11s 27ms/step - loss: 7.3756 - accuracy: 0.0000e+00 - recall_m: 9.5669 - precision_m: 0.5951 - f1_m: 1.1191 - val_loss: 11.4364 - val_accuracy: 0.0000e+00 - val_recall_m: 0.0000e+00 - val_precision_m: 0.0000e+00 - val_f1_m: 0.0000e+00
Epoch 5/100
421/421 [==============================] - 11s 26ms/step - loss: 7.3741 - accuracy: 0.0000e+00 - recall_m: 9.6217 - precision_m: 0.5941 - f1_m: 1.1177 - val_loss: 11.4364 - val_accuracy: 0.0000e+00 - val_recall_m: 0.0000e+00 - val_precision_m: 0.0000e+00 - val_f1_m: 0.0000e+00
Epoch 6/100
421/421 [==============================] - 11s 26ms/step - loss: 7.3777 - accuracy: 0.0000e+00 - recall_m: 9.6120 - precision_m: 0.5944 - f1_m: 1.1181 - val_loss: 11.4364 - val_accuracy: 0.0000e+00 - val_recall_m: 0.0000e+00 - val_precision_m: 0.0000e+00 - val_f1_m: 0.0000e+00
Epoch 7/100
421/421 [==============================] - 11s 26ms/step - loss: 7.3716 - accuracy: 0.0000e+00 - recall_m: 9.6052 - precision_m: 0.5946 - f1_m: 1.1184 - val_loss: 11.4364 - val_accuracy: 0.0000e+00 - val_recall_m: 0.0000e+00 - val_precision_m: 0.0000e+00 - val_f1_m: 0.0000e+00
Epoch 8/100
421/421 [==============================] - 11s 26ms/step - loss: 7.3564 - accuracy: 0.0000e+00 - recall_m: 9.6138 - precision_m: 0.5953 - f1_m: 1.1199 - val_loss: 11.4364 - val_accuracy: 0.0000e+00 - val_recall_m: 0.0000e+00 - val_precision_m: 0.0000e+00 - val_f1_m: 0.0000e+00
Epoch 9/100
421/421 [==============================] - 11s 26ms/step - loss: 7.3746 - accuracy: 0.0000e+00 - recall_m: 9.6138 - precision_m: 0.5945 - f1_m: 1.1185 - val_loss: 11.4364 - val_accuracy: 0.0000e+00 - val_recall_m: 0.0000e+00 - val_precision_m: 0.0000e+00 - val_f1_m: 0.0000e+00
Epoch 10/100
421/421 [==============================] - 11s 26ms/step - loss: 7.4833 - accuracy: 0.0000e+00 - recall_m: 8.9775 - precision_m: 0.5948 - f1_m: 1.1140 - val_loss: 10.4827 - val_accuracy: 0.0000e+00 - val_recall_m: 0.0000e+00 - val_precision_m: 0.0000e+00 - val_f1_m: 0.0000e+00
Epoch 11/100
421/421 [==============================] - 11s 26ms/step - loss: 7.5424 - accuracy: 0.0000e+00 - recall_m: 8.7890 - precision_m: 0.5934 - f1_m: 1.1105 - val_loss: 10.4827 - val_accuracy: 0.0000e+00 - val_recall_m: 0.0000e+00 - val_precision_m: 0.0000e+00 - val_f1_m: 0.0000e+00
Epoch 12/100
421/421 [==============================] - 11s 26ms/step - loss: 7.5478 - accuracy: 0.0000e+00 - recall_m: 8.7771 - precision_m: 0.5931 - f1_m: 1.1098 - val_loss: 10.4827 - val_accuracy: 0.0000e+00 - val_recall_m: 0.0000e+00 - val_precision_m: 0.0000e+00 - val_f1_m: 0.0000e+00
Epoch 13/100
421/421 [==============================] - 11s 26ms/step - loss: 7.5374 - accuracy: 0.0000e+00 - recall_m: 8.7926 - precision_m: 0.5938 - f1_m: 1.1112 - val_loss: 10.4827 - val_accuracy: 0.0000e+00 - val_recall_m: 0.0000e+00 - val_precision_m: 0.0000e+00 - val_f1_m: 0.0000e+00
Epoch 14/100
421/421 [==============================] - 11s 26ms/step - loss: 7.5104 - accuracy: 0.0000e+00 - recall_m: 8.8107 - precision_m: 0.5951 - f1_m: 1.1134 - val_loss: 10.4827 - val_accuracy: 0.0000e+00 - val_recall_m: 0.0000e+00 - val_precision_m: 0.0000e+00 - val_f1_m: 0.0000e+00
Epoch 15/100
421/421 [==============================] - 11s 26ms/step - loss: 7.5579 - accuracy: 0.0000e+00 - recall_m: 8.6188 - precision_m: 0.5946 - f1_m: 1.1109 - val_loss: 9.5291 - val_accuracy: 0.0000e+00 - val_recall_m: 0.0000e+00 - val_precision_m: 0.0000e+00 - val_f1_m: 0.0000e+00
Epoch 16/100
421/421 [==============================] - 11s 26ms/step - loss: 7.7537 - accuracy: 0.0000e+00 - recall_m: 7.5090 - precision_m: 0.5953 - f1_m: 1.1011 - val_loss: 8.5760 - val_accuracy: 0.0000e+00 - val_recall_m: 0.0000e+00 - val_precision_m: 0.0000e+00 - val_f1_m: 0.0000e+00
Epoch 17/100
421/421 [==============================] - 11s 26ms/step - loss: 7.8200 - accuracy: 0.0000e+00 - recall_m: 7.1960 - precision_m: 0.5949 - f1_m: 1.0970 - val_loss: 8.5760 - val_accuracy: 0.0000e+00 - val_recall_m: 0.0000e+00 - val_precision_m: 0.0000e+00 - val_f1_m: 0.0000e+00
Epoch 18/100
421/421 [==============================] - 11s 26ms/step - loss: 7.8189 - accuracy: 0.0000e+00 - recall_m: 7.2090 - precision_m: 0.5946 - f1_m: 1.0968 - val_loss: 8.5760 - val_accuracy: 0.0000e+00 - val_recall_m: 0.0000e+00 - val_precision_m: 0.0000e+00 - val_f1_m: 0.0000e+00
Epoch 19/100
421/421 [==============================] - 11s 26ms/step - loss: 7.8221 - accuracy: 0.0000e+00 - recall_m: 7.2236 - precision_m: 0.5945 - f1_m: 1.0968 - val_loss: 8.5760 - val_accuracy: 0.0000e+00 - val_recall_m: 0.0000e+00 - val_precision_m: 0.0000e+00 - val_f1_m: 0.0000e+00
Epoch 20/100
421/421 [==============================] - 11s 26ms/step - loss: 7.8434 - accuracy: 0.0000e+00 - recall_m: 7.1539 - precision_m: 0.5930 - f1_m: 1.0936 - val_loss: 8.5760 - val_accuracy: 0.0000e+00 - val_recall_m: 0.0000e+00 - val_precision_m: 0.0000e+00 - val_f1_m: 0.0000e+00
Epoch 21/100
421/421 [==============================] - 11s 26ms/step - loss: 7.8114 - accuracy: 0.0000e+00 - recall_m: 7.2156 - precision_m: 0.5951 - f1_m: 1.0978 - val_loss: 8.5761 - val_accuracy: 0.0000e+00 - val_recall_m: 0.0000e+00 - val_precision_m: 0.0000e+00 - val_f1_m: 0.0000e+00
Epoch 22/100
421/421 [==============================] - 11s 26ms/step - loss: 7.8140 - accuracy: 0.0000e+00 - recall_m: 7.2050 - precision_m: 0.5951 - f1_m: 1.0979 - val_loss: 8.5761 - val_accuracy: 0.0000e+00 - val_recall_m: 0.0000e+00 - val_precision_m: 0.0000e+00 - val_f1_m: 0.0000e+00
Epoch 23/100
421/421 [==============================] - 11s 27ms/step - loss: 7.8117 - accuracy: 0.0000e+00 - recall_m: 7.2241 - precision_m: 0.5952 - f1_m: 1.0980 - val_loss: 8.5761 - val_accuracy: 0.0000e+00 - val_recall_m: 0.0000e+00 - val_precision_m: 0.0000e+00 - val_f1_m: 0.0000e+00
Epoch 24/100
421/421 [==============================] - 11s 26ms/step - loss: 7.8239 - accuracy: 0.0000e+00 - recall_m: 7.2035 - precision_m: 0.5941 - f1_m: 1.0958 - val_loss: 8.5761 - val_accuracy: 0.0000e+00 - val_recall_m: 0.0000e+00 - val_precision_m: 0.0000e+00 - val_f1_m: 0.0000e+00
Epoch 25/100
421/421 [==============================] - 11s 27ms/step - loss: 7.8327 - accuracy: 0.0000e+00 - recall_m: 7.1842 - precision_m: 0.5938 - f1_m: 1.0953 - val_loss: 8.5761 - val_accuracy: 0.0000e+00 - val_recall_m: 0.0000e+00 - val_precision_m: 0.0000e+00 - val_f1_m: 0.0000e+00
Epoch 26/100
421/421 [==============================] - 11s 27ms/step - loss: 7.8394 - accuracy: 0.0000e+00 - recall_m: 7.1823 - precision_m: 0.5931 - f1_m: 1.0939 - val_loss: 8.5761 - val_accuracy: 0.0000e+00 - val_recall_m: 0.0000e+00 - val_precision_m: 0.0000e+00 - val_f1_m: 0.0000e+00