In [28]:
import numpy as np
import pandas as pd

In [29]:
results = pd.read_excel("../data/样本分析.xlsx")

In [30]:
results

,id,result20220311-3\n0.93926361227,result20220223-3\n0.86214143686,result20220224-1\n0.84045261879,result20220227-1\n0.85591428797
0,2533183958,√,√,√,√
1,2186749200,√,√,√,√
2,2445049876,√,√,√,√
3,2071313507,√,√,√,√
4,2745781539,√,√,√,√
5,2347718608,√,√,√,√
6,2496032641,√,√,√,√
7,179418058,√,√,√,√
8,179458306,√,√,√,√
9,1606708811,√,√,√,√
10,2319973783,√,√,√,√
11,2825175309,√,√,√,√
12,1916407803,√,√,√,√
13,179569820,√,√,√,√
14,2717225077,√,√,√,√
15,2759232590,√,√,√,√
16,2238809293,√,√,√,√
17,179547052,√,√,NaN,√
18,2741872006,√,√,√,√
19,2540517219,√,√,√,√
20,2523401557,√,√,√,√
21,2172970175,√,√,√,√
22,2347718610,√,√,√,√
23,2576321385,√,√,NaN,√
24,2256064355,√,√,NaN,√
25,855996491,√,√,√,√
26,2427050072,√,√,√,√
27,2212416005,√,NaN,NaN,√
28,1912367373,√,√,√,√
29,179457448,NaN,√,NaN,√
30,1862376457,NaN,√,NaN,NaN
31,2045098996,NaN,√,NaN,NaN
32,2625677315,NaN,√,√,NaN
33,2494025452,NaN,NaN,√,NaN
34,1954405682,NaN,NaN,NaN,NaN
35,179421630,NaN,NaN,√,NaN
36,1485790704,NaN,NaN,√,√
37,1862415085,NaN,NaN,√,NaN
38,2326835483,NaN,NaN,√,NaN
39,2212577893,NaN,NaN,√,NaN
40,2245541933,NaN,NaN,√,NaN
41,2451165982,NaN,NaN,√,√
42,2535198432,NaN,NaN,√,√
43,2624797677,NaN,NaN,√,√
44,2471562086,NaN,NaN,√,√
45,2486242927,NaN,NaN,√,NaN
46,2717225084,NaN,NaN,√,√
47,2852503463,NaN,NaN,√,NaN
48,2222664609,NaN,NaN,√,NaN
49,2817362052,NaN,NaN,√,NaN
50,179601986,NaN,NaN,NaN,√
51,1541520478,NaN,NaN,NaN,√
52,2268548573,NaN,NaN,NaN,√
53,179433516,NaN,NaN,NaN,√
54,2115712219,NaN,NaN,NaN,√

In [31]:
filename = "result20220223-3"
result = pd.read_csv("../data/" + filename + ".csv", skiprows=1)
with open("../data/" + filename + ".csv", "r") as f:
    score = f.readline()[6:-1]
column = filename + "\n" + score
column

'result20220223-3\n0.86214143686'

In [32]:
results[column] = np.nan

In [33]:
pred_pos = result[result["label"] == 1]
known = pd.read_csv("../data/known.csv")
pred_pos

               id  label
742     179418058      1
1802    179457448      1
1815    179458306      1
4127    179569085      1
5115    855996491      1
5190    874996400      1
6470   1606708811      1
6644   1862376457      1
6685   1912367373      1
6752   2045098996      1
6825   2071313507      1
7237   2347718608      1
7517   2238809293      1
7655   2271557820      1
7929   2533183958      1
8082   2625677315      1
8184   2496032641      1
8264   2427050072      1
8554   2717225077      1
8619   2741872006      1
8629   2745781539      1
8655   2759232590      1
8995    179569820      1
11594   179547052      1
13618  2172970175      1
13644  2186749200      1
13677  2194274407      1
13840  2251440776      1
13855  2256064355      1
13970  2319973783      1
14019  2347718610      1
14138  2445049876      1
14257  2479963778      1
14282  2494025452      1
14322  2523401557      1
14433  2533183961      1
14452  2540517219      1
14554  2576321385      1
14590  2602819207      1
14800  1916407803      1
14821  1954405682      1
15056  2759317616      1
15331  2825175309      1

In [34]:
for cons_id in pred_pos["id"].values.tolist():
    if cons_id in known["id"].values.tolist() and known[known["id"] == cons_id]["label"].iloc[0] == 0:
        continue
    if cons_id in results["id"].values.tolist():
        results.loc[results["id"] == cons_id, column] = "√"
    else:
        results.loc[max(results.index) + 1, "id"] = int(cons_id)
        results.loc[results["id"] == cons_id, column] = "√"

In [35]:
results["id"] = results["id"].apply(lambda x: int(x)).astype(str)
results

,id,result20220311-3\n0.93926361227,result20220223-3\n0.86214143686,result20220224-1\n0.84045261879,result20220227-1\n0.85591428797
0,2533183958,√,√,√,√
1,2186749200,√,√,√,√
2,2445049876,√,√,√,√
3,2071313507,√,√,√,√
4,2745781539,√,√,√,√
5,2347718608,√,√,√,√
6,2496032641,√,√,√,√
7,179418058,√,√,√,√
8,179458306,√,√,√,√
9,1606708811,√,√,√,√
10,2319973783,√,√,√,√
11,2825175309,√,√,√,√
12,1916407803,√,√,√,√
13,179569820,√,√,√,√
14,2717225077,√,√,√,√
15,2759232590,√,√,√,√
16,2238809293,√,√,√,√
17,179547052,√,√,NaN,√
18,2741872006,√,√,√,√
19,2540517219,√,√,√,√
20,2523401557,√,√,√,√
21,2172970175,√,√,√,√
22,2347718610,√,√,√,√
23,2576321385,√,√,NaN,√
24,2256064355,√,√,NaN,√
25,855996491,√,√,√,√
26,2427050072,√,√,√,√
27,2212416005,√,NaN,NaN,√
28,1912367373,√,√,√,√
29,179457448,NaN,√,NaN,√
30,1862376457,NaN,√,NaN,NaN
31,2045098996,NaN,NaN,NaN,NaN
32,2625677315,NaN,√,√,NaN
33,2494025452,NaN,NaN,√,NaN
34,1954405682,NaN,NaN,NaN,NaN
35,179421630,NaN,NaN,√,NaN
36,1485790704,NaN,NaN,√,√
37,1862415085,NaN,NaN,√,NaN
38,2326835483,NaN,NaN,√,NaN
39,2212577893,NaN,NaN,√,NaN
40,2245541933,NaN,NaN,√,NaN
41,2451165982,NaN,NaN,√,√
42,2535198432,NaN,NaN,√,√
43,2624797677,NaN,NaN,√,√
44,2471562086,NaN,NaN,√,√
45,2486242927,NaN,NaN,√,NaN
46,2717225084,NaN,NaN,√,√
47,2852503463,NaN,NaN,√,NaN
48,2222664609,NaN,NaN,√,NaN
49,2817362052,NaN,NaN,√,NaN
50,179601986,NaN,NaN,NaN,√
51,1541520478,NaN,NaN,NaN,√
52,2268548573,NaN,NaN,NaN,√
53,179433516,NaN,NaN,NaN,√
54,2115712219,NaN,NaN,NaN,√

In [36]:
results.to_excel("../data/样本分析.xlsx", index=False)