In [28]:
import numpy as np
import pandas as pd

In [29]:
results = pd.read_excel("../data/样本分析.xlsx")

In [30]:
results

,文件,result20220208-1,result20220208-2,result20220208-3,result20220209-1,result20220209-2,result20220209-3,result20220210-1,result20220210-2,result20220210-3,result20220211-1,result20220211-2,result20220212-1,result20220212-3,result20220214-1
0,2071313507,NaN,NaN,√,√,√,√,√,NaN,√,√,√,√,√,√
1,2533183958,NaN,NaN,√,√,√,√,√,NaN,√,√,√,√,NaN,√
2,2186749200,NaN,NaN,NaN,√,√,√,√,NaN,√,√,√,√,√,√
3,2445049876,NaN,NaN,√,√,√,√,√,NaN,√,√,√,√,√,√
4,2533183961,NaN,NaN,√,√,√,√,√,NaN,√,√,√,√,√,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1001,179404059,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,√
1002,179433228,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,√
1003,179547052,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,√
1004,179554514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,√
1005,1688684718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,√

In [31]:
filename = "result20220214-3"
if filename not in results.columns:
    results[filename] = np.nan

In [32]:
result = pd.read_csv("../data/" + filename + ".csv", skiprows=1)

In [33]:
result = result[result["label"] == 1]
result

               id  label
4618    179601986      1
5190    874996400      1
5292    887227796      1
5599   1429892107      1
5799   1476442068      1
...           ...    ...
14978  2055289586      1
15013  2734030826      1
15056  2759317616      1
15240  2115712219      1
15314  2817362052      1

[69 rows x 2 columns]

In [34]:
for cons_id in result["id"].values.tolist():
    if cons_id in results["文件"].values.tolist():
        results.loc[results["文件"] == cons_id, filename] = "√"
    else:
        results.loc[max(results.index) + 1, "文件"] = cons_id
        results.loc[results["文件"] == cons_id, filename] = "√"

In [35]:
# results = results.reindex(columns=sorted(results.columns))
results

,文件,result20220208-1,result20220208-2,result20220208-3,result20220209-1,result20220209-2,result20220209-3,result20220210-1,result20220210-2,result20220210-3,result20220211-1,result20220211-2,result20220212-1,result20220212-3,result20220214-1,result20220214-3
0,2.071314e+09,NaN,NaN,√,√,√,√,√,NaN,√,√,√,√,√,√,√
1,2.533184e+09,NaN,NaN,√,√,√,√,√,NaN,√,√,√,√,NaN,√,NaN
2,2.186749e+09,NaN,NaN,NaN,√,√,√,√,NaN,√,√,√,√,√,√,√
3,2.445050e+09,NaN,NaN,√,√,√,√,√,NaN,√,√,√,√,√,√,√
4,2.533184e+09,NaN,NaN,√,√,√,√,√,NaN,√,√,√,√,√,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,1.794332e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,√,NaN
1003,1.795471e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,√,NaN
1004,1.795545e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,√,NaN
1005,1.688685e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,√,√
1006,2.850055e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,√

In [36]:
results.to_excel("../data/样本分析.xlsx", index=False)