In [109]:
import numpy as np
import pandas as pd

In [110]:
results = pd.read_excel("../data/样本分析.xlsx")

In [111]:
results

,id,result20220313-3\n0.94764715408,result20220301-1\n0.87808506590,result20220227-3\n还差1个,result20220227-2\n0.72360916970,result20220227-1\n0.85591428797,result20220224-2\n0.86955341618,result20220224-1\n0.84045261879,result20220223-3\n0.86214143686,result20220223-2\n0.78359608457,result20220223-1\n0.74938074441,result20220214-3\n0.66866947030,result20220214-1\n0.73228887873,result20220301-2\n0.86453896211
0,2533183958,√,√,NaN,NaN,√,√,√,√,NaN,NaN,NaN,√,√
1,2186749200,√,√,√,√,√,√,√,√,√,√,√,√,√
2,2445049876,√,√,√,√,√,√,√,√,√,√,√,√,√
3,2071313507,√,√,√,√,√,√,√,√,√,√,√,√,√
4,2745781539,√,√,√,√,√,√,√,√,√,NaN,NaN,√,√
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,2576316686,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,√,NaN
163,179405779,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,√,NaN
164,179407055,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,√,NaN
165,179433228,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,√,NaN
166,179554514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,√,NaN

In [112]:
filename = "result20220301-3"
result = pd.read_csv("../data/" + filename + ".csv", skiprows=1)
with open("../data/" + filename + ".csv", "r") as f:
    score = f.readline()[6:-1]
column = filename + "\n" + score
column

'result20220301-3\n0.75862360388'

In [113]:
results[column] = np.nan

In [114]:
pred_pos = result[result["label"] == 1]
known = pd.read_csv("../data/known.csv")
pred_pos

               id  label
5115    855996491      1
5229    880030471      1
5292    887227796      1
6825   2071313507      1
6858   2098712195      1
7237   2347718608      1
7625   2268548573      1
7794   2451165982      1
7929   2533183958      1
7943   2535198432      1
7976   2576316686      1
8077   2624797677      1
8138   2471562086      1
8184   2496032641      1
8264   2427050072      1
8554   2717225077      1
8555   2717225078      1
8557   2717225084      1
8629   2745781539      1
8655   2759232590      1
8730   2777368824      1
8794   2817362051      1
12567   179558804      1
13556  2852503463      1
13618  2172970175      1
13637  2181712126      1
13644  2186749200      1
13677  2194274407      1
13717  2212416005      1
13840  2251440776      1
13970  2319973783      1
14019  2347718610      1
14138  2445049876      1
14433  2533183961      1
14554  2576321385      1
14590  2602819207      1
14616  2624797661      1
14731  2661974115      1
14771  2689150327      1
14800  1916407803      1
14956  2005271988      1
15195  2784950026      1
15320  2819680593      1
15331  2825175309      1

In [115]:
for cons_id in pred_pos["id"].values.tolist():
    if cons_id in known["id"].values.tolist() and known[known["id"] == cons_id]["label"].iloc[0] == 0:
        continue
    if cons_id in results["id"].values.tolist():
        results.loc[results["id"] == cons_id, column] = "√"
    else:
        results.loc[max(results.index) + 1, "id"] = int(cons_id)
        results.loc[results["id"] == cons_id, column] = "√"

In [116]:
results["id"] = results["id"].apply(lambda x: int(x)).astype(str)
results

,id,result20220313-3\n0.94764715408,result20220301-1\n0.87808506590,result20220227-3\n还差1个,result20220227-2\n0.72360916970,result20220227-1\n0.85591428797,result20220224-2\n0.86955341618,result20220224-1\n0.84045261879,result20220223-3\n0.86214143686,result20220223-2\n0.78359608457,result20220223-1\n0.74938074441,result20220214-3\n0.66866947030,result20220214-1\n0.73228887873,result20220301-2\n0.86453896211,result20220301-3\n0.75862360388
0,2533183958,√,√,NaN,NaN,√,√,√,√,NaN,NaN,NaN,√,√,√
1,2186749200,√,√,√,√,√,√,√,√,√,√,√,√,√,√
2,2445049876,√,√,√,√,√,√,√,√,√,√,√,√,√,√
3,2071313507,√,√,√,√,√,√,√,√,√,√,√,√,√,√
4,2745781539,√,√,√,√,√,√,√,√,√,NaN,NaN,√,√,√
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164,179407055,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,√,NaN,NaN
165,179433228,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,√,NaN,NaN
166,179554514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,√,NaN,NaN
167,2784950026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,√
168,2819680593,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,√

In [117]:
results.to_excel("../data/样本分析.xlsx", index=False)