In [28]:
import numpy as np
import pandas as pd

In [29]:
results = pd.read_excel("../data/样本分析.xlsx")

In [30]:
results

,文件,result20220208-1,result20220208-2,result20220208-3,result20220209-1,result20220209-2,result20220209-3,result20220210-1,result20220210-2,result20220210-3,...,result20220223-3,result20220224-1,result20220224-2,result20220227-1,result20220227-2,result20220227-3,result20220301-1,result20220301-2,result20220301-3,result20220302-1
0,2071313507,NaN,NaN,√,√,√,√,√,NaN,√,...,√,√,√,√,√,√,√,√,√,√
1,2533183958,NaN,NaN,√,√,√,√,√,NaN,√,...,√,√,√,√,NaN,NaN,√,√,√,√
2,2186749200,NaN,NaN,NaN,√,√,√,√,NaN,√,...,√,√,√,√,√,√,√,√,√,√
3,2445049876,NaN,NaN,√,√,√,√,√,NaN,√,...,√,√,√,√,√,√,√,√,√,√
4,2533183961,NaN,NaN,√,√,√,√,√,NaN,√,...,√,√,√,√,NaN,NaN,√,√,√,√
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1011,179571683,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,√,NaN,NaN,NaN,NaN,NaN
1012,179542235,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,√,NaN,NaN,NaN,NaN,NaN
1013,179442157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,√,NaN,NaN,NaN,NaN
1014,2625688232,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,√,NaN,NaN,NaN,NaN
1015,2755107753,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,√

In [31]:
filename = "result20220302-2"
if filename not in results.columns:
    results[filename] = np.nan

In [32]:
result = pd.read_csv("../data/" + filename + ".csv", skiprows=1)

In [33]:
result = result[result["label"] == 1]
result

               id  label
742     179418058      1
1815    179458306      1
5115    855996491      1
5190    874996400      1
6470   1606708811      1
6825   2071313507      1
7237   2347718608      1
7517   2238809293      1
7929   2533183958      1
8184   2496032641      1
8264   2427050072      1
8554   2717225077      1
8619   2741872006      1
8629   2745781539      1
8641   2755128229      1
8655   2759232590      1
8995    179569820      1
11594   179547052      1
13618  2172970175      1
13644  2186749200      1
13677  2194274407      1
13717  2212416005      1
13840  2251440776      1
13855  2256064355      1
13970  2319973783      1
14019  2347718610      1
14138  2445049876      1
14257  2479963778      1
14322  2523401557      1
14433  2533183961      1
14452  2540517219      1
14554  2576321385      1
14590  2602819207      1
14800  1916407803      1
15056  2759317616      1
15331  2825175309      1

In [34]:
for cons_id in result["id"].values.tolist():
    if cons_id in results["文件"].values.tolist():
        results.loc[results["文件"] == cons_id, filename] = "√"
    else:
        results.loc[max(results.index) + 1, "文件"] = cons_id
        results.loc[results["文件"] == cons_id, filename] = "√"

In [35]:
# results = results.reindex(columns=sorted(results.columns))
results

,文件,result20220208-1,result20220208-2,result20220208-3,result20220209-1,result20220209-2,result20220209-3,result20220210-1,result20220210-2,result20220210-3,...,result20220224-1,result20220224-2,result20220227-1,result20220227-2,result20220227-3,result20220301-1,result20220301-2,result20220301-3,result20220302-1,result20220302-2
0,2071313507,NaN,NaN,√,√,√,√,√,NaN,√,...,√,√,√,√,√,√,√,√,√,√
1,2533183958,NaN,NaN,√,√,√,√,√,NaN,√,...,√,√,√,NaN,NaN,√,√,√,√,√
2,2186749200,NaN,NaN,NaN,√,√,√,√,NaN,√,...,√,√,√,√,√,√,√,√,√,√
3,2445049876,NaN,NaN,√,√,√,√,√,NaN,√,...,√,√,√,√,√,√,√,√,√,√
4,2533183961,NaN,NaN,√,√,√,√,√,NaN,√,...,√,√,√,NaN,NaN,√,√,√,√,√
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1011,179571683,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,√,NaN,NaN,NaN,NaN,NaN,NaN
1012,179542235,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,√,NaN,NaN,NaN,NaN,NaN,NaN
1013,179442157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,√,NaN,NaN,NaN,NaN,NaN
1014,2625688232,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,√,NaN,NaN,NaN,NaN,NaN
1015,2755107753,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,√,NaN

In [36]:
results.to_excel("../data/样本分析.xlsx", index=False)